# Generated by Django 2.1.2 on 2018-11-04 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slambook', '0004_auto_20181104_0825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fdetail',
            options={'ordering': ['-pk']},
        ),
    ]
